### ISSUE TITLE
Remove padding-top for TextField if have no label

### ISSUE THREAD

**Issue by vczb** [vczb/sagu-ui#71]
CONTEXT:

if you do not set any label it looks weird

![image](https://user-images.githubusercontent.com/51221635/234553225-84d7cf9b-c32b-4b0f-a66d-55d499e53eb2.png)

It happens because the input element has a padding-top setted

![image](https://user-images.githubusercontent.com/51221635/234553373-91fbd0d8-2bad-405f-b642-fd01f3a2cbfd.png)
 
 ---
TODO:

In case of the label is not set remove the padding-top 

 ---

Please follow the best practices when implementing this solution

---
 
https://vczb.github.io/sagu-ui/?path=/story/textfield--default&args=label:

**Comment by Ksj14-kumar** [comment]
Hi, Can you assign this issue to me? I want to work on it.

**Comment by vczb** [comment]
> Hi, Can you assign this issue to me? I want to work on it.

Sure! go ahead :)

**Comment by Ksj14-kumar** [comment]
@vczb, Can you tell me how to install dependencies locally because when I run yarn install, it gives me an error. this error look like this>> yarn install v1.5.1
error An unexpected error occurred: "Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in F:\\allMy\\Projects\\Open-Sources\\sagu-ui\\yarn.lock".
info If you think this is a bug, please open a bug report with the information provided in "F:\\allMy\\Projects\\Open-Sources\\sagu-ui\\yarn-error.log".

**Comment by vczb** [comment]
> 

seems like this is an error on your `yarn` package. 

Please take a look at this issue: https://github.com/yarnpkg/yarn/issues/7100#issuecomment-634922887

**Comment by vczb** [comment]
Great job @Ksj14-kumar :1st_place_medal:
